# Generated by Django 3.2.22 on 2023-11-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=30)),
                ('branddescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=30)),
                ('categorydescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
                ('itemcode', models.CharField(max_length=10)),
                ('salestax', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('barcode', models.CharField(max_length=10)),
                ('hsncode', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=15)),
                ('purchasetax', models.IntegerField()),
                ('brand', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiapp.brandmaster')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiapp.categorymaster')),
            ],
        ),
    ]
