# Generated by Django 3.2.22 on 2023-11-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_doctormaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormaster',
            name='doctorname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientmaster',
            name='mobile1',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=50)),
                ('mobile1', models.CharField(max_length=20)),
                ('doctorname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('doctor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.doctormaster')),
                ('patient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientmaster')),
            ],
        ),
    ]
