# Generated by Django 3.2.22 on 2023-11-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_auto_20231104_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentname', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=70)),
            ],
        ),
    ]
