# Generated by Django 3.2.22 on 2023-11-06 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_treatmentmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=15)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dbp', models.IntegerField()),
                ('resrate', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('spo2', models.IntegerField()),
                ('sbp', models.IntegerField()),
                ('pulserate', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=3)),
                ('patient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientmaster')),
            ],
        ),
    ]
