# Generated by Django 3.2.22 on 2023-11-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_delete_vitalmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presno', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
