# Generated by Django 3.2.22 on 2023-11-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_vitalmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalmaster',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
