# Generated by Django 3.2.22 on 2023-11-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_alter_vitalmaster_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalmaster',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
