# Generated by Django 3.2.22 on 2023-11-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0012_auto_20231108_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriptionno', models.CharField(max_length=20)),
                ('complaints', models.TextField()),
                ('presentmedhis', models.TextField()),
                ('pastmedhis', models.TextField()),
                ('pastsurghis', models.TextField()),
                ('allergies', models.TextField()),
                ('investresult', models.TextField()),
                ('instruction', models.TextField()),
                ('vitals', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.vitalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentname', models.CharField(max_length=50)),
                ('treatmentdate', models.DateField()),
                ('treatmentduration', models.CharField(max_length=40)),
                ('consultation_model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.consultationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=30)),
                ('freequency', models.CharField(max_length=30)),
                ('medstartdate', models.DateField()),
                ('medenddate', models.DateField()),
                ('consultation_model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.consultationmodel')),
            ],
        ),
    ]
