# Generated by Django 3.2.22 on 2023-11-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0013_consultationmedicine_consultationmodel_consultationtreatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmedicine',
            name='consultation_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_medicines', to='patientapp.consultationmodel'),
        ),
        migrations.AlterField(
            model_name='consultationtreatment',
            name='consultation_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_treatments', to='patientapp.consultationmodel'),
        ),
    ]
