# Generated by Django 3.2.22 on 2023-11-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0015_vitalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vitalInfo',
        ),
    ]
