# Generated by Django 3.2.22 on 2023-11-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0017_vitalmaster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalmaster',
            name='date',
            field=models.DateField(),
        ),
    ]
