# Generated by Django 3.2.22 on 2023-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0018_alter_vitalmaster_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalmaster',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
