# Generated by Django 3.2.22 on 2023-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0019_alter_vitalmaster_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalmaster',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
