# Generated by Django 3.2.22 on 2023-11-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0020_alter_vitalmaster_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalmaster',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='dbp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='pulserate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='resrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='sbp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vitalmaster',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
