# Generated by Django 3.2.22 on 2023-11-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0021_auto_20231110_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmedicine',
            name='medicine_method',
            field=models.CharField(choices=[('ac', 'AC'), ('pc', 'PC')], default='AC', max_length=10),
            preserve_default=False,
        ),
    ]
